version: 0.2

# run-as: builder

env:
  shell: /bin/sh
#  variables:
#    key: "value"
#    key: "value"
#  parameter-store:
#    key: "value"
#    key: "value"
#  exported-variables:
#    - variable
#    - variable
#  secrets-manager:
#    key: secret-id:json-key:version-stage:version-id
#  git-credential-helper: no | yes

#proxy:
#  upload-artifacts: no | yes
#  logs: no | yes

#batch:
#  fast-fail: false | true
#  # build-list:
#  # build-matrix:
#  # build-graph:
        
phases:
  install:
#    run-as: Linux-user-name
    on-failure: ABORT # | CONTINUE
    runtime-versions:
      nodejs: latest
    commands:
      - exit 1
      - npm install -g @angular/cli
      - npm install
#    finally:
#      - command
#      - command
#  pre_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
#    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
  build:
#    run-as: Linux-user-name
    on-failure: ABORT # | CONTINUE
    commands:
      - ng build
      - ls dist/*/
#  post_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
#    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
#reports:
#  report-group-name-or-arn:
#    files:
#      - location
#      - location
#    base-directory: location
#    discard-paths: no | yes
#    file-format: report-format
artifacts:
  files:
    - dist/**/*
  name: $(date +%Y-%m-%d)
  discard-paths: yes
#  base-directory: 
#  exclude-paths: excluded paths
#  enable-symlinks: no | yes
#  s3-prefix: prefix
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      name: secondary-artifact-name
#      discard-paths: no | yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: no | yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
